export type Choice = { id: string; label: string }

export type SliderGroup = {
	name: string
	sliders: string[]
}

export const SLIDER_GROUPS: SliderGroup[] = [
	{
		name: 'Basic',
		sliders: ['Exposure', 'Contrast', 'Highlights', 'Shadows', 'Whites', 'Blacks'],
	},
	{
		name: 'Color',
		sliders: ['Temperature', 'Tint', 'Vibrance', 'Saturation'],
	},
	{
		name: 'Presence',
		sliders: ['Texture', 'Clarity', 'Dehaze'],
	},
	{
		name: 'Detail',
		sliders: [
			'Sharpness',
			'SharpenRadius',
			'SharpenDetail',
			'SharpenEdgeMasking',
			'LuminanceNR',
			'LuminanceNoiseReductionDetail',
			'LuminanceNoiseReductionContrast',
			'ColorNR',
			'ColorNoiseReductionDetail',
			'ColorNoiseReductionSmoothness',
		],
	},
	{
		name: 'Color Mixer / HSL',
		sliders: [
			'HueAdjustmentRed',
			'HueAdjustmentOrange',
			'HueAdjustmentYellow',
			'HueAdjustmentGreen',
			'HueAdjustmentAqua',
			'HueAdjustmentBlue',
			'HueAdjustmentPurple',
			'HueAdjustmentMagenta',
			'SaturationAdjustmentRed',
			'SaturationAdjustmentOrange',
			'SaturationAdjustmentYellow',
			'SaturationAdjustmentGreen',
			'SaturationAdjustmentAqua',
			'SaturationAdjustmentBlue',
			'SaturationAdjustmentPurple',
			'SaturationAdjustmentMagenta',
			'LuminanceAdjustmentRed',
			'LuminanceAdjustmentOrange',
			'LuminanceAdjustmentYellow',
			'LuminanceAdjustmentGreen',
			'LuminanceAdjustmentAqua',
			'LuminanceAdjustmentBlue',
			'LuminanceAdjustmentPurple',
			'LuminanceAdjustmentMagenta',
		],
	},
	{
		name: 'B&W Mixer',
		sliders: [
			'GrayMixerRed',
			'GrayMixerOrange',
			'GrayMixerYellow',
			'GrayMixerGreen',
			'GrayMixerAqua',
			'GrayMixerBlue',
			'GrayMixerPurple',
			'GrayMixerMagenta',
		],
	},
	{
		name: 'Effects',
		sliders: [
			'PostCropVignetteAmount',
			'PostCropVignetteMidpoint',
			'PostCropVignetteFeather',
			'PostCropVignetteRoundness',
			'PostCropVignetteHighlightContrast',
			'GrainAmount',
			'GrainSize',
			'GrainFrequency',
		],
	},
	{
		name: 'Calibration',
		sliders: ['ShadowTint', 'RedHue', 'RedSaturation', 'GreenHue', 'GreenSaturation', 'BlueHue', 'BlueSaturation'],
	},
	{
		name: 'Lens / Defringe',
		sliders: [
			'LensProfileDistortionScale',
			'LensProfileVignettingScale',
			'LensManualDistortionAmount',
			'DefringePurpleAmount',
			'DefringePurpleHueLo',
			'DefringePurpleHueHi',
			'DefringeGreenAmount',
			'DefringeGreenHueLo',
			'DefringeGreenHueHi',
		],
	},
	{
		name: 'Switches - Lens / Defringe',
		sliders: ['AutoLateralCA', 'LensProfileEnable'],
	},
	{
		name: 'Transform',
		sliders: [
			'PerspectiveVertical',
			'PerspectiveHorizontal',
			'PerspectiveRotate',
			'PerspectiveScale',
			'PerspectiveAspect',
			'PerspectiveX',
			'PerspectiveY',
		],
	},
	{
		name: 'Tone Curve',
		sliders: [
			'ParametricDarks',
			'ParametricLights',
			'ParametricShadows',
			'ParametricHighlights',
			'ParametricShadowSplit',
			'ParametricMidtoneSplit',
			'ParametricHighlightSplit',
		],
	},
]

export const SLIDER_LABELS: Record<string, string> = {
	Exposure: 'Exposure',
	Contrast: 'Contrast',
	Highlights: 'Highlights',
	Shadows: 'Shadows',
	Whites: 'Whites',
	Blacks: 'Blacks',
	Temperature: 'Temperature',
	Tint: 'Tint',
	Vibrance: 'Vibrance',
	Saturation: 'Saturation',
	Texture: 'Texture',
	Clarity: 'Clarity',
	Dehaze: 'Dehaze',
	Sharpness: 'Sharpness',
	SharpenRadius: 'Sharpen Radius',
	SharpenDetail: 'Sharpen Detail',
	SharpenEdgeMasking: 'Sharpen Masking',
	LuminanceNR: 'Luminance Noise Reduction',
	LuminanceNoiseReductionDetail: 'Luminance NR Detail',
	LuminanceNoiseReductionContrast: 'Luminance NR Contrast',
	ColorNR: 'Color Noise Reduction',
	ColorNoiseReductionDetail: 'Color NR Detail',
	ColorNoiseReductionSmoothness: 'Color NR Smoothness',
	HueAdjustmentRed: 'Hue Red',
	HueAdjustmentOrange: 'Hue Orange',
	HueAdjustmentYellow: 'Hue Yellow',
	HueAdjustmentGreen: 'Hue Green',
	HueAdjustmentAqua: 'Hue Aqua',
	HueAdjustmentBlue: 'Hue Blue',
	HueAdjustmentPurple: 'Hue Purple',
	HueAdjustmentMagenta: 'Hue Magenta',
	SaturationAdjustmentRed: 'Saturation Red',
	SaturationAdjustmentOrange: 'Saturation Orange',
	SaturationAdjustmentYellow: 'Saturation Yellow',
	SaturationAdjustmentGreen: 'Saturation Green',
	SaturationAdjustmentAqua: 'Saturation Aqua',
	SaturationAdjustmentBlue: 'Saturation Blue',
	SaturationAdjustmentPurple: 'Saturation Purple',
	SaturationAdjustmentMagenta: 'Saturation Magenta',
	LuminanceAdjustmentRed: 'Luminance Red',
	LuminanceAdjustmentOrange: 'Luminance Orange',
	LuminanceAdjustmentYellow: 'Luminance Yellow',
	LuminanceAdjustmentGreen: 'Luminance Green',
	LuminanceAdjustmentAqua: 'Luminance Aqua',
	LuminanceAdjustmentBlue: 'Luminance Blue',
	LuminanceAdjustmentPurple: 'Luminance Purple',
	LuminanceAdjustmentMagenta: 'Luminance Magenta',
	GrayMixerRed: 'B&W Red',
	GrayMixerOrange: 'B&W Orange',
	GrayMixerYellow: 'B&W Yellow',
	GrayMixerGreen: 'B&W Green',
	GrayMixerAqua: 'B&W Aqua',
	GrayMixerBlue: 'B&W Blue',
	GrayMixerPurple: 'B&W Purple',
	GrayMixerMagenta: 'B&W Magenta',
	PostCropVignetteAmount: 'Vignette Amount',
	PostCropVignetteMidpoint: 'Vignette Midpoint',
	PostCropVignetteFeather: 'Vignette Feather',
	PostCropVignetteRoundness: 'Vignette Roundness',
	PostCropVignetteHighlightContrast: 'Vignette Highlights',
	GrainAmount: 'Grain Amount',
	GrainSize: 'Grain Size',
	GrainFrequency: 'Grain Roughness',
	ShadowTint: 'Shadow Tint',
	RedHue: 'Red Primary Hue',
	RedSaturation: 'Red Primary Saturation',
	GreenHue: 'Green Primary Hue',
	GreenSaturation: 'Green Primary Saturation',
	BlueHue: 'Blue Primary Hue',
	BlueSaturation: 'Blue Primary Saturation',
	LensProfileDistortionScale: 'Profile Distortion',
	LensProfileEnable: 'Enable Profile Corrections',
	AutoLateralCA: 'Remove Chromatic Aberration',
	LensProfileVignettingScale: 'Profile Vignetting',
	LensManualDistortionAmount: 'Manual Distortion',
	DefringePurpleAmount: 'Purple Defringe Amount',
	DefringePurpleHueLo: 'Purple Hue Low',
	DefringePurpleHueHi: 'Purple Hue High',
	DefringeGreenAmount: 'Green Defringe Amount',
	DefringeGreenHueLo: 'Green Hue Low',
	DefringeGreenHueHi: 'Green Hue High',
	PerspectiveVertical: 'Transform Vertical',
	PerspectiveHorizontal: 'Transform Horizontal',
	PerspectiveRotate: 'Transform Rotate',
	PerspectiveScale: 'Transform Scale',
	PerspectiveAspect: 'Transform Aspect',
	PerspectiveX: 'Transform X Offset',
	PerspectiveY: 'Transform Y Offset',
	ParametricDarks: 'Curve Darks',
	ParametricLights: 'Curve Lights',
	ParametricShadows: 'Curve Shadows',
	ParametricHighlights: 'Curve Highlights',
	ParametricShadowSplit: 'Curve Shadow Split',
	ParametricMidtoneSplit: 'Curve Midtone Split',
	ParametricHighlightSplit: 'Curve Highlight Split',
}

export const FEEDBACK_SUPPORTED_SLIDERS: string[] = [
	'Exposure',
	'Contrast',
	'Highlights',
	'Shadows',
	'Whites',
	'Blacks',
	'Texture',
	'Clarity',
	'Dehaze',
	'Vibrance',
	'Saturation',
	'Sharpness',
	'SharpenRadius',
	'SharpenDetail',
	'SharpenEdgeMasking',
	'LuminanceNR',
	'LuminanceNoiseReductionDetail',
	'LuminanceNoiseReductionContrast',
	'ColorNR',
	'ColorNoiseReductionDetail',
	'ColorNoiseReductionSmoothness',
	'Temperature',
	'Tint',
	'HueAdjustmentRed',
	'HueAdjustmentOrange',
	'HueAdjustmentYellow',
	'HueAdjustmentGreen',
	'HueAdjustmentAqua',
	'HueAdjustmentBlue',
	'HueAdjustmentPurple',
	'HueAdjustmentMagenta',
	'SaturationAdjustmentRed',
	'SaturationAdjustmentOrange',
	'SaturationAdjustmentYellow',
	'SaturationAdjustmentGreen',
	'SaturationAdjustmentAqua',
	'SaturationAdjustmentBlue',
	'SaturationAdjustmentPurple',
	'SaturationAdjustmentMagenta',
	'LuminanceAdjustmentRed',
	'LuminanceAdjustmentOrange',
	'LuminanceAdjustmentYellow',
	'LuminanceAdjustmentGreen',
	'LuminanceAdjustmentAqua',
	'LuminanceAdjustmentBlue',
	'LuminanceAdjustmentPurple',
	'LuminanceAdjustmentMagenta',
	'GrayMixerRed',
	'GrayMixerOrange',
	'GrayMixerYellow',
	'GrayMixerGreen',
	'GrayMixerAqua',
	'GrayMixerBlue',
	'GrayMixerPurple',
	'GrayMixerMagenta',
	'PostCropVignetteAmount',
	'PostCropVignetteMidpoint',
	'PostCropVignetteFeather',
	'PostCropVignetteRoundness',
	'PostCropVignetteHighlightContrast',
	'GrainAmount',
	'GrainSize',
	'GrainFrequency',
	'ShadowTint',
	'RedHue',
	'RedSaturation',
	'GreenHue',
	'GreenSaturation',
	'BlueHue',
	'BlueSaturation',
	'LensProfileDistortionScale',
	'LensProfileVignettingScale',
	'LensManualDistortionAmount',
	'DefringePurpleAmount',
	'DefringePurpleHueLo',
	'DefringePurpleHueHi',
	'DefringeGreenAmount',
	'DefringeGreenHueLo',
	'DefringeGreenHueHi',
	'PerspectiveVertical',
	'PerspectiveHorizontal',
	'PerspectiveRotate',
	'PerspectiveScale',
	'PerspectiveAspect',
	'PerspectiveX',
	'PerspectiveY',
	'ParametricDarks',
	'ParametricLights',
	'ParametricShadows',
	'ParametricHighlights',
	'ParametricShadowSplit',
	'ParametricMidtoneSplit',
	'ParametricHighlightSplit',
]

export const LIGHTROOM_ACTIONS: Choice[] = [
	{ id: 'setAutoTone', label: 'Auto Tone' },
	{ id: 'setAutoWhiteBalance', label: 'Auto White Balance' },
	{ id: 'selectUprightTool', label: 'Select Upright Tool' },
	{ id: 'resetTransforms', label: 'Reset Transform' },
	{ id: 'selectCropTool', label: 'Select Crop Tool' },
	{ id: 'resetCrop', label: 'Reset Crop' },
	{ id: 'selectHealingTool', label: 'Select Healing Tool' },
	{ id: 'resetSpotRemoval', label: 'Reset Spot Removal' },
	{ id: 'selectRedEyeTool', label: 'Select Red Eye Tool' },
	{ id: 'resetRedeye', label: 'Reset Red Eye' },
	{ id: 'selectMaskingTool', label: 'Select Masking Tool' },
]

export const AUTO_ACTION_COOLDOWN_ACTIONS = ['setAutoTone', 'setAutoWhiteBalance']
export const AUTO_ACTION_COOLDOWN_MS = 2200

export const FALLBACK_SLIDERS: Choice[] = SLIDER_GROUPS.flatMap((group) =>
	group.sliders.map((slider) => ({
		id: slider,
		label: `${group.name} - ${SLIDER_LABELS[slider] || slider}`,
	}))
)

export const FALLBACK_GROUPS: Choice[] = SLIDER_GROUPS.map((group) => ({
	id: group.name,
	label: group.name,
}))

export function sliderVariableId(slider: string): string {
	return `slider_${slider.replace(/[^A-Za-z0-9]+/g, '_').toLowerCase()}`
}

export function sliderLabel(slider: string): string {
	return SLIDER_LABELS[slider] || slider
}
